version: "3.3"
services:
  postgres:
    image: "postgres:11"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=helpdesk-dev
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=helpdesk
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_local_dev:/var/lib/postgresql/data

  mailhog:
    image: jcalonso/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  postgres_data_local_dev:
